In [15]:
import sys
sys.path.insert(0,'/workspaces/RAG_secure_code_generation/src')
sys.path.insert(0,'/workspaces/RAG_secure_code_generation')
import pandas as pd
import os

In [16]:
summary_file = "../../experiments/task_detect_xss_simple_prompt/experiments_summary.csv"
output = "../../output/few_shot_experiments_{examples}_examples_top_{n}.csv"

In [17]:
parameters_to_keep = [
    "model_name",
    "temperature",
    "successes",
    "examples_per_class"  
]
top_k_parameters_to_keep = [
    "accuracy",
    "precision",
    "recall",
    "f1"
]

top_k = 10
examples_per_class = 20

In [18]:
seed = 156

In [19]:
output = output.format(examples=examples_per_class, n = top_k)
output

'../../output/few_shot_experiments_20_examples_top_10.csv'

In [20]:
parameters_to_keep.extend(list(map(lambda x: f"top_{top_k}_{x}",top_k_parameters_to_keep)))
parameters_to_keep

['model_name',
 'temperature',
 'successes',
 'examples_per_class',
 'top_10_accuracy',
 'top_10_precision',
 'top_10_recall',
 'top_10_f1']

In [21]:
df = pd.read_csv(summary_file)
df.head()

,Unnamed: 0,successes,failures,total,accuracy,accuracy_std,accuracy_var,precision,precision_std,precision_var,...,top_15_accuracy_var,top_15_precision,top_15_precision_std,top_15_precision_var,top_15_recall,top_15_recall_std,top_15_recall_var,top_15_f1,top_15_f1_std,top_15_f1_var
0,0,50,0,50,0.718765,0.148206,0.021965,0.928139,0.138496,0.019181,...,0.002311,0.923941,0.098112,0.009626,0.852387,0.111139,0.012352,0.876072,0.051881,0.002692
1,1,50,0,50,0.738455,0.134767,0.018162,0.917520,0.134003,0.017957,...,0.001109,0.918561,0.100400,0.010080,0.815788,0.126191,0.015924,0.850058,0.040719,0.001658
2,2,47,3,50,0.678764,0.165826,0.027498,0.961529,0.119094,0.014183,...,0.004680,0.999350,0.002054,0.000004,0.778447,0.135320,0.018312,0.868435,0.088921,0.007907
3,3,49,1,50,0.788162,0.159201,0.025345,0.956744,0.101042,0.010210,...,0.000318,0.997484,0.008984,0.000081,0.905528,0.035530,0.001262,0.948879,0.019180,0.000368
4,4,44,6,50,0.752529,0.164416,0.027033,0.937666,0.092455,0.008548,...,0.003578,0.943870,0.092799,0.008612,0.914042,0.088755,0.007877,0.922441,0.059281,0.003514

In [22]:
#keep only the rows with seed
df = df[df["seed"] == seed]
df.head()

,Unnamed: 0,successes,failures,total,accuracy,accuracy_std,accuracy_var,precision,precision_std,precision_var,...,top_15_accuracy_var,top_15_precision,top_15_precision_std,top_15_precision_var,top_15_recall,top_15_recall_std,top_15_recall_var,top_15_f1,top_15_f1_std,top_15_f1_var
0,0,50,0,50,0.718765,0.148206,0.021965,0.928139,0.138496,0.019181,...,0.002311,0.923941,0.098112,0.009626,0.852387,0.111139,0.012352,0.876072,0.051881,0.002692
1,1,50,0,50,0.738455,0.134767,0.018162,0.917520,0.134003,0.017957,...,0.001109,0.918561,0.100400,0.010080,0.815788,0.126191,0.015924,0.850058,0.040719,0.001658
2,2,47,3,50,0.678764,0.165826,0.027498,0.961529,0.119094,0.014183,...,0.004680,0.999350,0.002054,0.000004,0.778447,0.135320,0.018312,0.868435,0.088921,0.007907
3,3,49,1,50,0.788162,0.159201,0.025345,0.956744,0.101042,0.010210,...,0.000318,0.997484,0.008984,0.000081,0.905528,0.035530,0.001262,0.948879,0.019180,0.000368
4,4,44,6,50,0.752529,0.164416,0.027033,0.937666,0.092455,0.008548,...,0.003578,0.943870,0.092799,0.008612,0.914042,0.088755,0.007877,0.922441,0.059281,0.003514

In [23]:
#filter keeping only generation mode few_shot
df = df[df["generation_mode"] == "few_shot"]
df.head()

,Unnamed: 0,successes,failures,total,accuracy,accuracy_std,accuracy_var,precision,precision_std,precision_var,...,top_15_accuracy_var,top_15_precision,top_15_precision_std,top_15_precision_var,top_15_recall,top_15_recall_std,top_15_recall_var,top_15_f1,top_15_f1_std,top_15_f1_var
3,3,49,1,50,0.788162,0.159201,0.025345,0.956744,0.101042,0.010210,...,0.000318,0.997484,8.983960e-03,8.071153e-05,0.905528,0.035530,0.001262,0.948879,0.019180,0.000368
4,4,44,6,50,0.752529,0.164416,0.027033,0.937666,0.092455,0.008548,...,0.003578,0.943870,9.279892e-02,8.611639e-03,0.914042,0.088755,0.007877,0.922441,0.059281,0.003514
5,5,43,7,50,0.809243,0.143294,0.020533,0.976206,0.064623,0.004176,...,0.000533,0.996366,8.409656e-03,7.072231e-05,0.877480,0.049900,0.002490,0.932271,0.025922,0.000672
6,6,48,2,50,0.839732,0.133960,0.017945,0.960295,0.080615,0.006499,...,0.000277,0.993019,1.885470e-02,3.554999e-04,0.933917,0.033025,0.001091,0.962072,0.017392,0.000302
7,7,45,5,50,0.842596,0.171854,0.029534,0.953071,0.088988,0.007919,...,0.000006,0.999811,9.504667e-07,9.033870e-13,0.964641,0.004883,0.000024,0.981905,0.002521,0.000006

In [24]:
#filtering keeping only examples_per_class
df = df[df["examples_per_class"] == examples_per_class]
df.head()

,Unnamed: 0,successes,failures,total,accuracy,accuracy_std,accuracy_var,precision,precision_std,precision_var,...,top_15_accuracy_var,top_15_precision,top_15_precision_std,top_15_precision_var,top_15_recall,top_15_recall_std,top_15_recall_var,top_15_f1,top_15_f1_std,top_15_f1_var
6,6,48,2,50,0.839732,1.339603e-01,1.794537e-02,0.960295,0.080615,0.006499,...,2.773177e-04,0.993019,1.885470e-02,3.554999e-04,0.933917,0.033025,0.001091,0.962072,1.739174e-02,3.024727e-04
7,7,45,5,50,0.842596,1.718545e-01,2.953396e-02,0.953071,0.088988,0.007919,...,6.087947e-06,0.999811,9.504667e-07,9.033870e-13,0.964641,0.004883,0.000024,0.981905,2.521430e-03,6.357610e-06
8,8,50,0,50,0.848777,1.368889e-01,1.873857e-02,0.954434,0.115510,0.013343,...,1.678812e-04,0.996386,9.384983e-03,8.807791e-05,0.932555,0.024882,0.000619,0.963210,1.359986e-02,1.849562e-04
30,30,40,10,50,0.621538,1.613810e-01,2.604384e-02,0.974120,0.096611,0.009334,...,4.364971e-03,0.963962,9.521175e-02,9.065277e-03,0.690251,0.113073,0.012785,0.794391,8.405832e-02,7.065801e-03
31,31,44,6,50,0.499723,5.551115e-17,3.081488e-33,1.000000,0.000000,0.000000,...,2.773339e-32,1.000000,0.000000e+00,0.000000e+00,0.010035,0.000000,0.000000,0.019870,3.469447e-18,1.203706e-35

In [25]:
#keep only the parameters we want
df = df[parameters_to_keep]
df.head()

,model_name,temperature,successes,examples_per_class,top_10_accuracy,top_10_precision,top_10_recall,top_10_f1
6,gpt-4-1106-preview,0.5,48,20,0.971980,0.997072,0.947382,0.971404
7,gpt-4-1106-preview,0.0,45,20,0.983054,0.999811,0.966648,0.982944
8,gpt-4-1106-preview,1.0,50,20,0.970828,0.996541,0.945667,0.970303
30,gpt-3.5-turbo-0613,0.5,40,20,0.860160,0.999979,0.723299,0.837651
31,gpt-3.5-turbo-0613,0.0,44,20,0.499723,1.000000,0.010035,0.019870

In [26]:
#set the precision of the metrics to 3f
df = df.round(3)
df.head()

,model_name,temperature,successes,examples_per_class,top_10_accuracy,top_10_precision,top_10_recall,top_10_f1
6,gpt-4-1106-preview,0.5,48,20,0.972,0.997,0.947,0.971
7,gpt-4-1106-preview,0.0,45,20,0.983,1.000,0.967,0.983
8,gpt-4-1106-preview,1.0,50,20,0.971,0.997,0.946,0.970
30,gpt-3.5-turbo-0613,0.5,40,20,0.860,1.000,0.723,0.838
31,gpt-3.5-turbo-0613,0.0,44,20,0.500,1.000,0.010,0.020

In [27]:
#drop examples_per_class column
df = df.drop(columns=["examples_per_class"])
df.head()

,model_name,temperature,successes,top_10_accuracy,top_10_precision,top_10_recall,top_10_f1
6,gpt-4-1106-preview,0.5,48,0.972,0.997,0.947,0.971
7,gpt-4-1106-preview,0.0,45,0.983,1.000,0.967,0.983
8,gpt-4-1106-preview,1.0,50,0.971,0.997,0.946,0.970
30,gpt-3.5-turbo-0613,0.5,40,0.860,1.000,0.723,0.838
31,gpt-3.5-turbo-0613,0.0,44,0.500,1.000,0.010,0.020

In [28]:
#sort by model name and by temperature
df = df.sort_values(by=["model_name", "temperature"])
df.head()

,model_name,temperature,successes,top_10_accuracy,top_10_precision,top_10_recall,top_10_f1
31,gpt-3.5-turbo-0613,0.0,44,0.500,1.000,0.010,0.020
30,gpt-3.5-turbo-0613,0.5,40,0.860,1.000,0.723,0.838
32,gpt-3.5-turbo-0613,1.0,46,0.862,1.000,0.728,0.840
7,gpt-4-1106-preview,0.0,45,0.983,1.000,0.967,0.983
6,gpt-4-1106-preview,0.5,48,0.972,0.997,0.947,0.971

In [29]:
len(df)

6

In [30]:
#save the dataframe
df.to_csv(output, index=False)